parameters:
  - name: deployenvironmentname
    default: DEVINT
  - name: DCountenv
    default: DEV
  - name: BuildContext
    default: Guest
  - name: DockerFileName
    default: Guest
  - name: checkoutreponame
    default: Reponame
  - name: ValidationType
    default: CAST
  - name: DockerFilePath
    default: Guest
  - name: DockerFolderPath
    default: Guest
  - name: deployenvironmentportfolio
    default: BC
variables:
- group: AKSDeployment-SVG
- group: 5088-AKSDeploymentFiles-VG
- group: AKSDeployment-DR-SVG
- name: envname
  value: DEV
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
  - name: envname
    value: SIT
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
  - name: envname
    value: DEV
- name: devKeyVaultSecret
  value: '--from-literal=AZURE_OPENAI_API_KEY="$(DEV-5088-wa-userengagementfrontend-azure-openai-api-key)" --from-literal=DB_CONNECTION_STRING="$(DEV-5088-wa-userengagementfrontend-db-connection-string)"'
- name: sitKeyVaultSecret
  value: '--from-literal=AZURE_OPENAI_API_KEY="$(SIT-5088-wa-userengagementfrontend-azure-openai-api-key)" --from-literal=DB_CONNECTION_STRING="$(SIT-5088-wa-userengagementfrontend-db-connection-string)"'
- name: ptKeyVaultSecret
  value: '--from-literal=AZURE_OPENAI_API_KEY="$(PT-5088-wa-userengagementfrontend-azure-openai-api-key)" --from-literal=DB_CONNECTION_STRING="$(PT-5088-wa-userengagementfrontend-db-connection-string)"'
- name: uatKeyVaultSecret
  value: '--from-literal=AZURE_OPENAI_API_KEY="$(UAT-5088-wa-userengagementfrontend-azure-openai-api-key)" --from-literal=DB_CONNECTION_STRING="$(UAT-5088-wa-userengagementfrontend-db-connection-string)"'
- name: prodKeyVaultSecret
  value: '--from-literal=AZURE_OPENAI_API_KEY="$(PROD-5088-wa-userengagementfrontend-azure-openai-api-key)" --from-literal=DB_CONNECTION_STRING="$(PROD-5088-wa-userengagementfrontend-db-connection-string)"'
- name: drKeyVaultSecret
  value: '--from-literal=AZURE_OPENAI_API_KEY="$(DR-5088-wa-userengagementfrontend-azure-openai-api-key)" --from-literal=DB_CONNECTION_STRING="$(DR-5088-wa-userengagementfrontend-db-connection-string)"'
pr: none
name: $(envname)-$(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: Digital-Platform-IT-Build/OneC_2932_CoreTemplate
      endpoint: GHA-Fulfilment IT Systems-SC-5088-User Engagement App
    - repository: Reponame
      type: githubenterprise
      ref: $(Build.SourceBranchName)
      name: Fulfilment-IT-Systems/OneC_5088_UserEngFrontEnd
      endpoint: GHA-Fulfilment IT Systems-SC-5088-User Engagement App
    - repository: Reponame
      type: githubenterprise
      ref: master
      name: Fulfilment-IT-Systems/5088-AKSDeploymentFiles
      endpoint: GHA-Fulfilment IT Systems-SC-5088-User Engagement App
stages:
  - template: AKS Core Template/AKSStages.yml@templates
    parameters:
      TrackName: 5088-wa-userengagementfrontend
      TrackVariableName: 5088-UserEngagementFrontEnd
      deployenvironmentname: DEVINT
      checkoutreponame: Reponame
      DCountenv: DEV
      TemplateName: AKS-Deploy-Logic.yml
      ValidationType: CAST
      BuildContext: .
      ISKTLO: false
      KTLOChildName: $(system.teamProject)
      DockerFileName: Dockerfile
      DockerFolderPath: $(Build.SourcesDirectory)/
      FilePath: \\CTSINAZSIDOPBS1\DevopsFileShare\AKS-devops\$(Build.SourceBranchName)\$(Build.DefinitionName)\$(Build.BuildNumber)\
      YAMLFolderName: 5088-AKSDeploymentFiles
      TrackType: WEB
      deployenvironmentportfolio: BC
      IsSVGRequired: True
      AKSPipelineIdVariable: 1018
